export ZSH="$HOME/.oh-my-zsh"

# set the directory i want to store zinit and plugins in;
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit.zinit.git"

# download zinit , if it's not there yet
if [ ! -d "$ZINIT_HOME" ]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# source / load zinit
source "${ZINIT_HOME}/zinit.zsh"


ZSH_THEME="robbyrussell"
#ZSH_THEME="agnoster"

plugins=(
	git
	bundler
	dotenv
	npm
	zsh-autosuggestions
	zsh-syntax-highlighting
  spotify
)

source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'

source ~/.profile

# --------------------------------------------------------------------------------------
# My personal configuration
source ~/.zshAlias/sail.zsh
source ~/.zshAlias/laravel.zsh
source ~/.zshAlias/react.zsh
source ~/.zshAlias/tmux.zsh
source ~/.zshAlias/services.zsh
source ~/.zshAlias/mvn.zsh
source ~/.zshAlias/git.zsh
source ~/.zshAlias/auto-sug.zsh
source ~/.zshAlias/keybindings.zsh


# Load Angular CLI autocompletion.
source <(ng completion script)

eval "$(zoxide init zsh)"
#eval "$(oh-my-posh init zsh)"

############ this one is to load home brew
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

neofetch

alias kitty=" kitty --start-as fullscreen"

export CLANG_FORMAT_STYLE=file:$HOME/.clang-format
export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
export PATH=$JAVA_HOME/bin:$PATH

export PATH=$PATH:$HOME/go/bin

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

